trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  - group: xamarin-android-aab
  - name: buildConfiguration
    value: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_6_0
  displayName: "Select the Xamarin SDK version"
  enabled: true

- task: DownloadSecureFile@1
  name: keyStore
  displayName: "Download keystore from secure files"
  inputs:
    secureFile: production.jks

- task: PublishBuildArtifacts@1
  displayName: 'Publish release'
  inputs:
    pathToPublish: 'drop'
    artifactName: 'release'
