- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*.csproj'
    target: 'XamarinFormsSpecialFolders.sln'
    outputDirectory: '$(build.binariesDirectory)/bin/Release'
    clean: true
    msbuildVersionOption: 'latest'
    msbuildArguments: 'MSBuild'
    jdkOption: 'JDKVersion'